// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/color-themes/CoralIndigo.tsx": () => import("../components/mockups/color-themes/CoralIndigo.tsx"),
  "./components/mockups/color-themes/GoldEmerald.tsx": () => import("../components/mockups/color-themes/GoldEmerald.tsx"),
  "./components/mockups/color-themes/PurpleCyan.tsx": () => import("../components/mockups/color-themes/PurpleCyan.tsx")
};
